name: Redirect Optimizer
run-name: Optimize redirects file
on:
  workflow_dispatch:
  pull_request:
  
# check for deleted/renamed
jobs:
  redirects-needed:
    name: Redirects needed?
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Get renamed/deleted files
        id: renamed-deleted-files
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for deleted or renamed files
        run: |
          echo $(git remote --verbose)
          echo $(pwd)
          echo "Current Repository: ${{ github.repository }}"
          echo "Current Branch: ${{ github.ref }}"
          echo "Branch Name: ${{ github.ref_name }}"
      - name: Update the PR Description
        uses: MongoCaleb/pr-description-action@master
        with:
          content: "- [ ] Do you need redirects for the following files?\n- - ${{ steps.renamed-deleted-files.outputs.deleted_files }}"
          token: ${{ secrets.GITHUB_TOKEN }}
